project_id = "sfvuuzpmsgepooeamkin"

[functions.public-create-appointment-request]
verify_jwt = false

[functions.public-get-availability-slots]
verify_jwt = false

[functions.setup-demo-user]
verify_jwt = false
