project_id = "sfvuuzpmsgepooeamkin"

[functions.public-create-appointment-request]
verify_jwt = false

[functions.public-get-availability-slots]
verify_jwt = false

[functions.public-get-available-starts]
verify_jwt = false

[functions.setup-demo-user]
verify_jwt = false

[functions.get-clinic-manifest]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.send-resend-email]
verify_jwt = false

[functions.process-scheduled-reminders]
verify_jwt = false

[functions.create-session-payment]
verify_jwt = false

[functions.public-patient-lookup]
verify_jwt = false
