// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { processLock } from '@supabase/auth-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Lock POR PESTAÑA en lugar del navigatorLock por defecto. El navigatorLock
    // usa un único candado del navegador compartido entre TODAS las pestañas y
    // cada consulta pasa por él para leer el token: si una pestaña lo retiene
    // (refresh de token, pestaña frenada en background), las demás quedan con
    // el preloader infinito. processLock serializa dentro de cada pestaña sin
    // bloquear a las otras; el refresh concurrente entre pestañas es tolerado
    // por la ventana de reuso de refresh tokens de Supabase.
    lock: processLock,
  }
});